// <auto-generated />
using System;
using Library.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190605185945_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Library.Infrastructure.Book", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorName");

                    b.Property<string>("AuthorSurname");

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<DateTime>("DateOfUpdate");

                    b.Property<int>("NumberOfSites");

                    b.Property<string>("PublishingHouse");

                    b.Property<string>("Title");

                    b.Property<int>("YearOfPublication");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Library.Infrastructure.Model.RentInfo", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("BookId");

                    b.Property<long?>("BorrowingUserId");

                    b.Property<DateTime>("DateFrom");

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<DateTime>("DateOfUpdate");

                    b.Property<DateTime>("DateTo");

                    b.Property<long?>("RentedBookId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowingUserId");

                    b.HasIndex("RentedBookId");

                    b.HasIndex("UserId");

                    b.ToTable("RentInfo");
                });

            modelBuilder.Entity("Library.Infrastructure.User", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<DateTime>("DateOfUpdate");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Library.Infrastructure.Model.RentInfo", b =>
                {
                    b.HasOne("Library.Infrastructure.Book")
                        .WithMany("RentInfos")
                        .HasForeignKey("BookId");

                    b.HasOne("Library.Infrastructure.User", "BorrowingUser")
                        .WithMany()
                        .HasForeignKey("BorrowingUserId");

                    b.HasOne("Library.Infrastructure.Book", "RentedBook")
                        .WithMany()
                        .HasForeignKey("RentedBookId");

                    b.HasOne("Library.Infrastructure.User")
                        .WithMany("RentInfos")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
